//load// java/lang/Queue
var java_util_Deque = _defineInterface("java_util_Deque",[java_util_Queue]);  

// -- methods:
// boolean	add(E e)
// void	addFirst(E e)
// void	addLast(E e)
// Iterator<E>	descendingIterator()
// E	element()
// E	getFirst()
// E	getLast()
// boolean	offer(E e)
// boolean	offerFirst(E e)
// boolean	offerLast(E e)
// E	peek()
// E	peekFirst()
// E	peekLast()
// E	poll()
// E	pollFirst()
// E	pollLast()
// E	pop()
// void	push(E e)
// E	remove()
// boolean	remove(Object o)
// E	removeFirst()
// boolean	removeFirstOccurrence(Object o)
// E	removeLast()
// boolean	removeLastOccurrence(Object o)

// -- methods inherited from Collection:
// boolean	contains(Object o)
// boolean	containsAll(Collection<?> c)
// boolean	equals(Object o)
// int	hashCode()
// boolean	isEmpty()
// Iterator<E>	iterator()
// int	size()
// Object[]	toArray()
// <T> T[]	toArray(T[] a)
