//load// java/util/Collection
var java_util_List = _defineInterface("java_util_List",[java_util_Collection]);  

// -- methods:
// boolean add(E e)
// void add(int index, E element)
// boolean	addAll(Collection<? extends E> c)
// boolean	addAll(int index, Collection<? extends E> c)
// void	clear()
// boolean	contains(Object o)
// boolean	containsAll(Collection<?> c)
// boolean	equals(Object o)
// E get(int index)
// int	hashCode()
// int	indexOf(Object o)
// boolean	isEmpty()
// Iterator<E>	iterator()
// int	lastIndexOf(Object o)
// E remove(int index)
// boolean	remove(Object o)
// boolean	removeAll(Collection<?> c)
// boolean	retainAll(Collection<?> c)
// E	set(int index, E element)
// int	size()
// Object[]	toArray()
// <T> T[]	toArray(T[] a)
